### ISSUE TITLE
Install instructions missing

### ISSUE THREAD

**Issue by Chavohawk** [akaihola/pgtricks#2]
Hello,

I understand that this will help sorting out Databases but how do I install it on my ubuntu - Postgresqsl?

Thanks,

**Comment by akaihola** [comment]
You're right, instructions for installing the utilities are missing from the README file. I'll add them. Meanwhile, you can run this on Ubuntu:
```bash
pip install --user https://github.com/akaihola/pgtricks/archive/0.9.1.tar.gz
pg_dump_splitsort my_database_dump.sql
```
