### ISSUE TITLE
Document the utility for splitting schema-only dumps

### ISSUE THREAD

**Issue by tyctor** [akaihola/pgtricks#4]
Hi

i tryied your `pg_dump_splitsort.py`, but result is only single file `0000_prologue.sql` which contain all lines from dump.
is there some special arguments needed for invoking `pg_dump`, to produce output which your script is accepting?
i only use simple `pd_dump -s database > db_dump.sql`

thanks for any advice

**Comment by akaihola** [comment]
No arguments are needed. The script is designed for full dumps with both schema and data, though. I haven't tested it with schema-only dumps.

**Comment by akaihola** [comment]
In current `master` there's the separate tool `pg_split_schema_dump.py` for splitting schema-only dumps. It needs
- documentation
- a console script entry point

I'll consider this issue completed only after I've added those.
